### PR TITLE
Supporting Fedora

### PR DESCRIPTION
**Pull request by eidins**
Same as the other PR's for Fedora.

### CODE REVIEW

**Comment by eidins** [comment]
Install on Fedora 34 failing with,

```
Error: Transaction test error:
  file /usr/lib/mozilla from install of firefox-pkcs11-loader-3.13.6-1.x86_64 conflicts with file from package mozilla-filesystem-1.9-25.fc34.x86_64
  file /usr/share/mozilla from install of firefox-pkcs11-loader-3.13.6-1.x86_64 conflicts with file from package mozilla-filesystem-1.9-25.fc34.x86_64
  file /usr/share/mozilla/extensions from install of firefox-pkcs11-loader-3.13.6-1.x86_64 conflicts with file from package mozilla-filesystem-1.9-25.fc34.x86_64
  file /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384} from install of firefox-pkcs11-loader-3.13.6-1.x86_64 conflicts with file from package firefox-95.0.2-2.fc34.x86_64
```

**Comment by metsma** [comment]
Can you add signed of to commit messages
https://github.com/open-eid/org/blob/master/CONTRIBUTING.md
Can you change CPACK_PACKAGE_CONTACT to something else as I understand this is not you?
You can use least same contact as in debian package

**Comment by eidins** [comment]
Since this isn't very useful without https://github.com/open-eid/chrome-token-signing in Fedora, I'll just close. https://github.com/open-eid/chrome-token-signing will be too difficult to package for Fedora because it's not using `cmake`.

Furthermore, the https://github.com/web-eid project seems to be the new thing and has more support for other countries eIDs

**Comment by metsma** [comment]
This package is still needed with web-eid, cases where website uses TLS auth

**Comment by eidins** [comment]
@metsma Is the chrome-token-signing needed for web-eid? If so, I can work on packaging that, but it'll take a bit of time.

**Comment by metsma** [comment]
No web-eid will replace chrome-token-signing

**Comment by eidins** [comment]
Can't figure out how to remove the EXCLUDE statements. Marking ready for review.

**Comment by metsma** [comment]
Is there way add dependencies with CPACK? If so can you add opensc-pkcs11 as deps.

**Review by metsma — APPROVED** [review]

**Pull request merged**
